defaults:
  - _self_
  - model: esm_concat 

# Task name
task_name: "affinity"

# --- TRANSFER LEARNING ---
pretrained_ckpt_path: null

# Resume path to a specific .ckpt file (e.g., "outputs/.../checkpoints/last.ckpt")
resume_checkpoint_path: null

data:
  base_csv: "data/dummy/base_data.csv"
  lookup_csv: "data/dummy/lookup_data.csv"
  num_workers: 6
  weight_col: null
  balance_clusters: false

training:
  seed: 42
  
  # Split
  split_strategy: "random"

  # Batch and Steps
  batch_size: 16
  accumulate_grad_batches: 2
  max_epochs: 5

  # Optimizer
  learning_rate: 5e-5  
  weight_decay: 1e-2
  warmup_ratio: 0.1

  # Callback
  monitor_metric: "val_loss"
  monitor_mode: "min"

  # Early Stopping
  early_stopping: true
  patience: 3

  # Hardware
  accelerator: "auto"
  devices: "auto"
  strategy: "ddp_find_unused_parameters_true"
  precision: "bf16-mixed"

  # Stability
  gradient_clip_val: 1.0
  gradient_clip_algorithm: "norm"
  val_check_interval: 0.5    # Validate every half epoch

  wandb:
    project: "affinity-finetune"

# Standard Hydra Output
hydra:
  run:
    dir: outputs/phase2_affinity/${now:%Y-%m-%d}/${now:%H-%M-%S}
