defaults:
  - _self_
  - model: esm_cross_attn

# Task name
task_name: "pair_dms"

# Resume path to a specific .ckpt file (e.g., "outputs/.../checkpoints/last.ckpt")
resume_checkpoint_path: null

data:
  mutant_csv: "data/dummy_dms/mutants.csv"
  wt_csv: "data/dummy_dms/wildtypes.csv"
  pairs_per_anchor: 3
  min_margin: 0.3
  max_pairs_per_protein: 2000
  crop_method: "smart"
  invert_score: false
  num_workers: 6
  balance_clusters: true
  balance_power: 0.25  

training:
  seed: 42
  split_strategy: "group"
  train_val_split: 0.9

  # Batch and Steps
  batch_size: 2
  accumulate_grad_batches: 16
  max_epochs: 5

  # Loss Function
  margin: 0.1                # Margin for MarginRankingLoss (diff between scores must be > this)

  # Optimizer
  learning_rate: 1e-4  
  weight_decay: 1e-2
  warmup_ratio: 0.1

  # Model saving 
  monitor_metric: "val_loss"              # Metric to monitor: "val_loss", "val_spearman", "test_spearman"
  monitor_mode: "min"                         # "min" for loss, "max" for spearman/accuracy

  # Early stopping
  early_stopping: true
  early_stopping_patience: 3                  # Stop after N epochs without improvement

  # Hardware
  accelerator: "auto"
  devices: "auto"
  strategy: "auto"
  precision: "bf16-mixed"

  # Stability
  gradient_clip_val: 1.0
  gradient_clip_algorithm: "norm"
  val_check_interval: 0.5    

  wandb:
    project: "dms-pretrain"

# Hydra handles the output path logic
hydra:
  run:
    dir: outputs/phase1_pair_dms/${now:%Y-%m-%d}/${now:%H-%M-%S}
