import sys
import os
import pandas as pd
import numpy as np
import scipy.stats as stats
import matplotlib.pyplot as plt
import seaborn as sns
import argparse
from sklearn.metrics import (
    mean_squared_error, 
    mean_absolute_error, 
    r2_score,
    roc_auc_score, 
    average_precision_score
)

# ---------------------
# Configuration
# ---------------------
LOWER_IS_BETTER = True  # True for log(Kd) where lower is tighter binding
BINARY_THRESHOLD = 3    # Threshold for defining an "Active" (True Binder)
# ---------------------

def calculate_enrichment_factor(y_true, y_pred, top_percent, binary_threshold):
    n_total = len(y_true)
    n_top = int(n_total * (top_percent / 100.0))
    if n_top == 0: n_top = 1

    if LOWER_IS_BETTER:
        actives_mask = y_true <= binary_threshold
    else:
        actives_mask = y_true >= binary_threshold

    total_actives = actives_mask.sum()
    if total_actives == 0: return 0.0
    background_rate = total_actives / n_total

    # Sort based on predicted logKd (Lower is predicted to be better)
    sorted_indices = np.argsort(y_pred)
    top_indices = sorted_indices[:n_top]
    
    hits_in_top = actives_mask[top_indices].sum()
    return (hits_in_top / n_top) / background_rate

def analyze_column(df, pred_col, target_col, output_dir, base_name):
    print(f"\n--- Analyzing Column: {pred_col} ---")
    
    y_true = df[target_col].values
    y_pred = df[pred_col].values

    # Correlation Metrics (Scale-invariant)
    spearman_rho, _ = stats.spearmanr(y_true, y_pred)
    pearson_r, _ = stats.pearsonr(y_true, y_pred)
    
    # Classification Metrics
    y_bin = (y_true <= BINARY_THRESHOLD).astype(int)
    # We negate y_pred for AUC because roc_auc_score expects higher scores = more likely positive
    # Since y_pred is logKd, lower is more likely positive.
    auroc = roc_auc_score(y_bin, -y_pred)
    
    ef_10 = calculate_enrichment_factor(y_true, y_pred, 10.0, BINARY_THRESHOLD)

    print(f"Spearman Rho : {spearman_rho:.4f}")
    print(f"AUROC        : {auroc:.4f}")
    print(f"EF @ 10%     : {ef_10:.2f}x")

    # Plotting
    plt.figure(figsize=(8, 6))
    sns.set_theme(style="ticks")
    
    # Scatter plot with regression line (using negated values for visualization)
    sns.regplot(x=-y_pred, y=-y_true, 
                scatter_kws={'alpha':0.5, 's':20}, 
                line_kws={'color':'red'})
    
    plt.title(f"Zero-Shot: {pred_col}")
    plt.xlabel(f"-{pred_col}")
    plt.ylabel("-Ground Truth (log_Aff)")
    
    plot_path = os.path.join(output_dir, f"{base_name}_{pred_col}_plot.png")
    plt.savefig(plot_path, dpi=300, bbox_inches='tight')
    plt.close()

def main(csv_path):
    df = pd.read_csv(csv_path)
    output_dir = os.path.dirname(csv_path)
    base_name = os.path.splitext(os.path.basename(csv_path))[0]
    
    target_col = "log_Aff"
    # Identify zero-shot columns generated by the previous script
    zs_cols = [c for c in df.columns if "zero_shot" in c]
    
    if not zs_cols:
        print("[Error] No zero-shot columns found in CSV.")
        return

    for col in zs_cols:
        analyze_column(df, col, target_col, output_dir, base_name)

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("path", type=str, help="Path to zero_shot_results.csv")
    args = parser.parse_args()
    main(args.path)
